// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7e8XAFtYcFxzBHiRDU2T-xcqQvogh1kM',
    appId: '1:514204840159:web:6a52d1faeffab9f812f96a',
    messagingSenderId: '514204840159',
    projectId: 'flutter-chat-3811e',
    authDomain: 'flutter-chat-3811e.firebaseapp.com',
    storageBucket: 'flutter-chat-3811e.appspot.com',
    measurementId: 'G-D9CHGXB49D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuEUOVE_G7SVC2cVBfQcGj_T86vRXserA',
    appId: '1:514204840159:android:6639d7e98f8a189312f96a',
    messagingSenderId: '514204840159',
    projectId: 'flutter-chat-3811e',
    storageBucket: 'flutter-chat-3811e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjn8jEd4LyAFosMImWHe6qb2nONXxbRlU',
    appId: '1:514204840159:ios:004ea1b758f3664912f96a',
    messagingSenderId: '514204840159',
    projectId: 'flutter-chat-3811e',
    storageBucket: 'flutter-chat-3811e.appspot.com',
    iosClientId:
        '514204840159-7qljoh2bna1n37icjc8fb9kff9cecq6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjn8jEd4LyAFosMImWHe6qb2nONXxbRlU',
    appId: '1:514204840159:ios:004ea1b758f3664912f96a',
    messagingSenderId: '514204840159',
    projectId: 'flutter-chat-3811e',
    storageBucket: 'flutter-chat-3811e.appspot.com',
    iosClientId:
        '514204840159-7qljoh2bna1n37icjc8fb9kff9cecq6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
